export default ({ state, html }) => html`
    <div class="category__wrapper">
        <div class="page__header"> ${state.title} </div>
        <div class="content">
            <div data-component="appSearch"></div>
        </div>
        <div class="content category__items">
            <div 
                data-component="appCategoryItem"
                data-label="Categoria"
            ></div>
            <div 
                data-component="appCategoryItem"
                data-label="Categoria"
            ></div>
            <div 
                data-component="appCategoryItem"
                data-label="Categoria"
            ></div>
            <div 
                data-component="appCategoryItem"
                data-label="Categoria"
            ></div>
            <div 
                data-component="appCategoryItem"
                data-label="Categoria"
            ></div>
            <div 
                data-component="appCategoryItem"
                data-label="Categoria"
            ></div>
            <div 
                data-component="appCategoryItem"
                data-label="Categoria"
            ></div>
            <div 
                data-component="appCategoryItem"
                data-label="Categoria"
            ></div>
            <div 
                data-component="appCategoryItem"
                data-label="Categoria"
            ></div>
            <div 
                data-component="appCategoryItem"
                data-label="Categoria"
            ></div>
            <div 
                data-component="appCategoryItem"
                data-label="Categoria"
            ></div>
            <div 
                data-component="appCategoryItem"
                data-label="Categoria"
            ></div>
            <div 
                data-component="appCategoryItem"
                data-label="Categoria"
            ></div>
            <div 
                data-component="appCategoryItem"
                data-label="Categoria"
            ></div>
            <div 
                data-component="appCategoryItem"
                data-label="Categoria"
            ></div>
        </div>
    </div>
`